#!/usr/bin/env python3
"""Upload helper for news.html content — generated by the hourly market-news automation.
This file contains the full HTML content and is committed by GITHUB_COMMIT_MULTIPLE_FILES.
"""
NEWS_HTML = r"""__NEWS_HTML_PLACEHOLDER__"""
